### ISSUE TITLE
DenseNet.jl is missing

### ISSUE THREAD

**Issue by dimarkov** [fabricerosay/AlphaGPU#1]
Hi thanks for the repo. A cool place for me to start learning julia programming for GPUs.

I have trouble running training routines. I tried executing the following code 
```
julia --project mainReversi6x6.jl
```

and ended up with an error
```
ERROR: LoadError: SystemError: opening file "/run/media/dima/data/Dropbox/development/julia/AlphaGPU/DenseNet.jl": No such file or directory
```
I cannot find DenseNet.jl in the repo, unlike the other files which are imported with ```include(...)```.

Would appreciate some help with figuring this out.

**Comment by fabricerosay** [comment]
Oups I uploaded the missing file, it should work.
I will upload a new version, much faster,  very soon.

**Comment by dimarkov** [comment]
Thanks! I am looking forward to it.

**Comment by dimarkov** [comment]
P.S. I just tested the code with the new DensNet.jl. The MCTS part runs super fast, but the code breaks during the training

```
sample acquis: 3249
longueur moyenne des parties: 32.49
taille du buffer: 3249
epoque: 1
batch number: 0
ERROR: LoadError: Mutating arrays is not supported
```

Just a small request without opening a new issue. Before you update the code with new super fast version, please check that Reversi also works :)

**Comment by fabricerosay** [comment]
What game was it and how many games did you launch? You got less samples
than a single batch, I think that's why it errored.
I'm not at home till Wednesday, I will make the changes then.

**Comment by fabricerosay** [comment]
Hello I did a major update increasing speed a lot on game with board
size>=7 and improving stability. I did a quick test and added reversi 8x8.
I'll be happy to hear if things work for you.

F.

**Comment by fabricerosay** [comment]
Hello did a change, but cannot test it atm, did you try it?
