### ISSUE TITLE
Network information missing for reversi 8x8

### ISSUE THREAD

**Issue by dimarkov** [fabricerosay/AlphaGPU#4]
Hi, I tried testing the new reversi 8x8 files and it seems that this line of code fails
`JLD2.@load "DataReversi8/reseau100.json" reseau`
The file is missing in the master branch and also other branches as far as I can see.

**Comment by fabricerosay** [comment]
Hi reversi 8x8 should now work, net is 8x dense(512x512).
I forgot to change reversi 6x6 but it should be easy starting from mainreversi8x8 all you have to change is the line importing the game(game module is also called revsix)
As for speed it should be  at least 100 times faster than suragnair, I believe. (32k games in less than a minute)
Depending on what you need, you should check alphazero. jl, it is slower than alphagpu but way more polished and should work with bigger games, and also order of magnitude faster than the implementation you are referring too.
Ps: hex should also work and hex 7x7 should give you a good idea of the speed.
